const sample = ".......S.......
.......^.......
......^.^......
.....^.^.^.....
....^.^...^....
...^.^...^.^...
..^...^.....^..
.^.^.^.^.^...^."
def part-2 [] {
  let prisms = {}
  $sample | lines | each {|l| ($l | split chars) | enumerate } | enumerate 
}

def main [] {
  part-2
}
